Repository kserve/modelmesh-runtime-adapter, pull requests merged in 2023-10, with the labels that each got.

#55 Fixing model disk size evaluation for pvc
  model-serving-puller/puller/puller.go
  model-serving-puller/puller/puller_test.go
Labels: approved, lgtm

#57 doc: Add developer instructions
  README.md
  model-mesh-torchserve-adapter/.gitignore
  scripts/build_docker.sh
  scripts/run_tests.sh
Labels: documentation, approved, lgtm

#58 chore: Ensure consistent version of generate proto stubs
  Dockerfile
  internal/proto/kfserving-predict-v2/inference.pb.go
  internal/proto/kfserving-predict-v2/inference_grpc.pb.go
  internal/proto/mlserver/dataplane/dataplane.pb.go
  internal/proto/mlserver/dataplane/dataplane_grpc.pb.go
  internal/proto/mmesh/model-mesh.pb.go
  internal/proto/mmesh/model-mesh_grpc.pb.go
  internal/proto/mmesh/model-runtime.pb.go
  internal/proto/mmesh/model-runtime_grpc.pb.go
  internal/proto/torchserve/inference.pb.go
  internal/proto/torchserve/inference_grpc.pb.go
  internal/proto/torchserve/management.pb.go
  internal/proto/torchserve/management_grpc.pb.go
  internal/proto/triton/model_config.pb.go
  internal/proto/triton/triton.pb.go
  internal/proto/triton/triton_grpc.pb.go
Labels: approved, lgtm

#61 chore: Update gRPC dependencies
  go.mod
  go.sum
Labels: approved, lgtm

#63 chore: Update runtime image from ubi8/ubi-minimal:8.7 to 8.8
  Dockerfile
Labels: approved, lgtm

#62 chore: Update filepath secure join
  .gitignore
  go.mod
  go.sum
Labels: approved, lgtm

#66 chore: Reuse existing developer image
  Makefile
  scripts/build_docker.sh
  scripts/develop.sh
Labels: approved

#65 chore: Add CodeQL configuration
  .github/workflows/codeql.yml
Labels: approved
